services:
  bites-auth-api:
    image: ${REPO}/bites-auth-api:${TAG}
    env_file:
      - .env
    networks:
      - bites-api
    ports:
      - 8080:8080

networks:
  bites-api:
    external: true
