version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    environment:
      TAG: ${CIRCLE_TAG}
    steps:
      - checkout
      - run:
          name: Build docker image
          command: make build
      - run:
          name: Log in to hub.docker.com
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Publish docker image
          command: make push
  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
      steps:
        - checkout
        - run:
            name: Create deployment manifest
            command: |
              # Replace the placeholders in the manifest with the intended values.
              # This is to avoid hardcoding the image name in the manifest, to make this
              # demo project more portable.
              BUILD_DATE=$(date '+%Y%m%d%H%M%S')
              cat deployment/bites-auth-api.deployment.yaml.template |\
                 sed "s|DOCKER_IMAGE|<< parameters.docker-image-name >>|g" \
              > deployment/bites-auth-api.deployment.yaml
        - aws-eks/update-kubeconfig-with-authenticator:
            cluster-name: << parameters.cluster-name >>
            install-kubectl: true
            aws-region: << parameters.aws-region >>
        - kubernetes/create-or-update-resource:
            resource-file-path: "deployment/bites-auth-api.deployment.yaml"
            get-rollout-status: true
            resource-name: deployment/bite-auth-api
        - kubernetes/create-or-update-resource:
            resource-file-path: "deployment/bites-auth-api.deployment.yaml"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy-application:
          cluster-name: bitbites
          aws-region: $AWS_DEFAULT_REGION
          docker-image-name: "${REPO}/bites-auth-api:${TAG}"
          version-info: "${TAG}"
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
